// <auto-generated />
using System;
using Intex2026API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Intex2026API.Migrations
{
    [DbContext(typeof(LighthouseContext))]
    [Migration("20260406203601_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Intex2026API.Models.Donation", b =>
                {
                    b.Property<string>("DonationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("donation_id");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("TEXT")
                        .HasColumnName("amount");

                    b.Property<string>("CampaignName")
                        .HasColumnType("TEXT")
                        .HasColumnName("campaign_name");

                    b.Property<string>("ChannelSource")
                        .HasColumnType("TEXT")
                        .HasColumnName("channel_source");

                    b.Property<string>("CurrencyCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("currency_code");

                    b.Property<DateOnly?>("DonationDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("donation_date");

                    b.Property<string>("DonationType")
                        .HasColumnType("TEXT")
                        .HasColumnName("donation_type");

                    b.Property<decimal?>("EstimatedValue")
                        .HasColumnType("TEXT")
                        .HasColumnName("estimated_value");

                    b.Property<string>("ImpactUnit")
                        .HasColumnType("TEXT")
                        .HasColumnName("impact_unit");

                    b.Property<string>("IsRecurring")
                        .HasColumnType("TEXT")
                        .HasColumnName("is_recurring");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("ReferralPostId")
                        .HasColumnType("TEXT")
                        .HasColumnName("referral_post_id");

                    b.Property<string>("SupporterId")
                        .HasColumnType("TEXT")
                        .HasColumnName("supporter_id");

                    b.HasKey("DonationId");

                    b.ToTable("donations", (string)null);
                });

            modelBuilder.Entity("Intex2026API.Models.DonationAllocation", b =>
                {
                    b.Property<string>("AllocationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("allocation_id");

                    b.Property<DateOnly?>("AllocationDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("allocation_date");

                    b.Property<string>("AllocationNotes")
                        .HasColumnType("TEXT")
                        .HasColumnName("allocation_notes");

                    b.Property<decimal?>("AmountAllocated")
                        .HasColumnType("TEXT")
                        .HasColumnName("amount_allocated");

                    b.Property<string>("DonationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("donation_id");

                    b.Property<string>("ProgramArea")
                        .HasColumnType("TEXT")
                        .HasColumnName("program_area");

                    b.Property<string>("SafehouseId")
                        .HasColumnType("TEXT")
                        .HasColumnName("safehouse_id");

                    b.HasKey("AllocationId");

                    b.ToTable("donation_allocations", (string)null);
                });

            modelBuilder.Entity("Intex2026API.Models.EducationRecord", b =>
                {
                    b.Property<string>("EducationRecordId")
                        .HasColumnType("TEXT")
                        .HasColumnName("education_record_id");

                    b.Property<decimal?>("AttendanceRate")
                        .HasColumnType("TEXT")
                        .HasColumnName("attendance_rate");

                    b.Property<string>("CompletionStatus")
                        .HasColumnType("TEXT")
                        .HasColumnName("completion_status");

                    b.Property<string>("EducationLevel")
                        .HasColumnType("TEXT")
                        .HasColumnName("education_level");

                    b.Property<string>("EnrollmentStatus")
                        .HasColumnType("TEXT")
                        .HasColumnName("enrollment_status");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<decimal?>("ProgressPercent")
                        .HasColumnType("TEXT")
                        .HasColumnName("progress_percent");

                    b.Property<DateOnly?>("RecordDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("record_date");

                    b.Property<string>("ResidentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("resident_id");

                    b.Property<string>("SchoolName")
                        .HasColumnType("TEXT")
                        .HasColumnName("school_name");

                    b.HasKey("EducationRecordId");

                    b.ToTable("education_records", (string)null);
                });

            modelBuilder.Entity("Intex2026API.Models.HealthWellbeingRecord", b =>
                {
                    b.Property<string>("HealthRecordId")
                        .HasColumnType("TEXT")
                        .HasColumnName("health_record_id");

                    b.Property<decimal?>("Bmi")
                        .HasColumnType("TEXT")
                        .HasColumnName("bmi");

                    b.Property<string>("DentalCheckupDone")
                        .HasColumnType("TEXT")
                        .HasColumnName("dental_checkup_done");

                    b.Property<decimal?>("EnergyLevelScore")
                        .HasColumnType("TEXT")
                        .HasColumnName("energy_level_score");

                    b.Property<decimal?>("GeneralHealthScore")
                        .HasColumnType("TEXT")
                        .HasColumnName("general_health_score");

                    b.Property<decimal?>("HeightCm")
                        .HasColumnType("TEXT")
                        .HasColumnName("height_cm");

                    b.Property<string>("MedicalCheckupDone")
                        .HasColumnType("TEXT")
                        .HasColumnName("medical_checkup_done");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<decimal?>("NutritionScore")
                        .HasColumnType("TEXT")
                        .HasColumnName("nutrition_score");

                    b.Property<string>("PsychologicalCheckupDone")
                        .HasColumnType("TEXT")
                        .HasColumnName("psychological_checkup_done");

                    b.Property<DateOnly?>("RecordDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("record_date");

                    b.Property<string>("ResidentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("resident_id");

                    b.Property<decimal?>("SleepQualityScore")
                        .HasColumnType("TEXT")
                        .HasColumnName("sleep_quality_score");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("TEXT")
                        .HasColumnName("weight_kg");

                    b.HasKey("HealthRecordId");

                    b.ToTable("health_wellbeing_records", (string)null);
                });

            modelBuilder.Entity("Intex2026API.Models.HomeVisitation", b =>
                {
                    b.Property<string>("VisitationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("visitation_id");

                    b.Property<string>("FamilyCooperationLevel")
                        .HasColumnType("TEXT")
                        .HasColumnName("family_cooperation_level");

                    b.Property<string>("FamilyMembersPresent")
                        .HasColumnType("TEXT")
                        .HasColumnName("family_members_present");

                    b.Property<string>("FollowUpNeeded")
                        .HasColumnType("TEXT")
                        .HasColumnName("follow_up_needed");

                    b.Property<string>("FollowUpNotes")
                        .HasColumnType("TEXT")
                        .HasColumnName("follow_up_notes");

                    b.Property<string>("LocationVisited")
                        .HasColumnType("TEXT")
                        .HasColumnName("location_visited");

                    b.Property<string>("Observations")
                        .HasColumnType("TEXT")
                        .HasColumnName("observations");

                    b.Property<string>("Purpose")
                        .HasColumnType("TEXT")
                        .HasColumnName("purpose");

                    b.Property<string>("ResidentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("resident_id");

                    b.Property<string>("SafetyConcernsNoted")
                        .HasColumnType("TEXT")
                        .HasColumnName("safety_concerns_noted");

                    b.Property<string>("SocialWorker")
                        .HasColumnType("TEXT")
                        .HasColumnName("social_worker");

                    b.Property<DateOnly?>("VisitDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("visit_date");

                    b.Property<string>("VisitOutcome")
                        .HasColumnType("TEXT")
                        .HasColumnName("visit_outcome");

                    b.Property<string>("VisitType")
                        .HasColumnType("TEXT")
                        .HasColumnName("visit_type");

                    b.HasKey("VisitationId");

                    b.ToTable("home_visitations", (string)null);
                });

            modelBuilder.Entity("Intex2026API.Models.InKindDonationItem", b =>
                {
                    b.Property<string>("ItemId")
                        .HasColumnType("TEXT")
                        .HasColumnName("item_id");

                    b.Property<string>("DonationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("donation_id");

                    b.Property<decimal?>("EstimatedUnitValue")
                        .HasColumnType("TEXT")
                        .HasColumnName("estimated_unit_value");

                    b.Property<string>("IntendedUse")
                        .HasColumnType("TEXT")
                        .HasColumnName("intended_use");

                    b.Property<string>("ItemCategory")
                        .HasColumnType("TEXT")
                        .HasColumnName("item_category");

                    b.Property<string>("ItemName")
                        .HasColumnType("TEXT")
                        .HasColumnName("item_name");

                    b.Property<string>("Quantity")
                        .HasColumnType("TEXT")
                        .HasColumnName("quantity");

                    b.Property<string>("ReceivedCondition")
                        .HasColumnType("TEXT")
                        .HasColumnName("received_condition");

                    b.Property<string>("UnitOfMeasure")
                        .HasColumnType("TEXT")
                        .HasColumnName("unit_of_measure");

                    b.HasKey("ItemId");

                    b.ToTable("in_kind_donation_items", (string)null);
                });

            modelBuilder.Entity("Intex2026API.Models.IncidentReport", b =>
                {
                    b.Property<string>("IncidentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("incident_id");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("FollowUpRequired")
                        .HasColumnType("TEXT")
                        .HasColumnName("follow_up_required");

                    b.Property<DateOnly?>("IncidentDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("incident_date");

                    b.Property<string>("IncidentType")
                        .HasColumnType("TEXT")
                        .HasColumnName("incident_type");

                    b.Property<string>("ReportedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("reported_by");

                    b.Property<string>("ResidentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("resident_id");

                    b.Property<DateOnly?>("ResolutionDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("resolution_date");

                    b.Property<string>("Resolved")
                        .HasColumnType("TEXT")
                        .HasColumnName("resolved");

                    b.Property<string>("ResponseTaken")
                        .HasColumnType("TEXT")
                        .HasColumnName("response_taken");

                    b.Property<string>("SafehouseId")
                        .HasColumnType("TEXT")
                        .HasColumnName("safehouse_id");

                    b.Property<string>("Severity")
                        .HasColumnType("TEXT")
                        .HasColumnName("severity");

                    b.HasKey("IncidentId");

                    b.ToTable("incident_reports", (string)null);
                });

            modelBuilder.Entity("Intex2026API.Models.InterventionPlan", b =>
                {
                    b.Property<string>("PlanId")
                        .HasColumnType("TEXT")
                        .HasColumnName("plan_id");

                    b.Property<DateOnly?>("CaseConferenceDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("case_conference_date");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("PlanCategory")
                        .HasColumnType("TEXT")
                        .HasColumnName("plan_category");

                    b.Property<string>("PlanDescription")
                        .HasColumnType("TEXT")
                        .HasColumnName("plan_description");

                    b.Property<string>("ResidentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("resident_id");

                    b.Property<string>("ServicesProvided")
                        .HasColumnType("TEXT")
                        .HasColumnName("services_provided");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<DateOnly?>("TargetDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("target_date");

                    b.Property<decimal?>("TargetValue")
                        .HasColumnType("TEXT")
                        .HasColumnName("target_value");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("PlanId");

                    b.ToTable("intervention_plans", (string)null);
                });

            modelBuilder.Entity("Intex2026API.Models.Partner", b =>
                {
                    b.Property<string>("PartnerId")
                        .HasColumnType("TEXT")
                        .HasColumnName("partner_id");

                    b.Property<string>("ContactName")
                        .HasColumnType("TEXT")
                        .HasColumnName("contact_name");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("end_date");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("PartnerName")
                        .HasColumnType("TEXT")
                        .HasColumnName("partner_name");

                    b.Property<string>("PartnerType")
                        .HasColumnType("TEXT")
                        .HasColumnName("partner_type");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT")
                        .HasColumnName("phone");

                    b.Property<string>("Region")
                        .HasColumnType("TEXT")
                        .HasColumnName("region");

                    b.Property<string>("RoleType")
                        .HasColumnType("TEXT")
                        .HasColumnName("role_type");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("PartnerId");

                    b.ToTable("partners", (string)null);
                });

            modelBuilder.Entity("Intex2026API.Models.PartnerAssignment", b =>
                {
                    b.Property<string>("AssignmentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("assignment_id");

                    b.Property<DateOnly?>("AssignmentEnd")
                        .HasColumnType("TEXT")
                        .HasColumnName("assignment_end");

                    b.Property<DateOnly?>("AssignmentStart")
                        .HasColumnType("TEXT")
                        .HasColumnName("assignment_start");

                    b.Property<string>("IsPrimary")
                        .HasColumnType("TEXT")
                        .HasColumnName("is_primary");

                    b.Property<string>("PartnerId")
                        .HasColumnType("TEXT")
                        .HasColumnName("partner_id");

                    b.Property<string>("ProgramArea")
                        .HasColumnType("TEXT")
                        .HasColumnName("program_area");

                    b.Property<string>("ResponsibilityNotes")
                        .HasColumnType("TEXT")
                        .HasColumnName("responsibility_notes");

                    b.Property<decimal?>("SafehouseId")
                        .HasColumnType("TEXT")
                        .HasColumnName("safehouse_id");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("AssignmentId");

                    b.ToTable("partner_assignments", (string)null);
                });

            modelBuilder.Entity("Intex2026API.Models.ProcessRecording", b =>
                {
                    b.Property<string>("RecordingId")
                        .HasColumnType("TEXT")
                        .HasColumnName("recording_id");

                    b.Property<string>("ConcernsFlagged")
                        .HasColumnType("TEXT")
                        .HasColumnName("concerns_flagged");

                    b.Property<string>("EmotionalStateEnd")
                        .HasColumnType("TEXT")
                        .HasColumnName("emotional_state_end");

                    b.Property<string>("EmotionalStateObserved")
                        .HasColumnType("TEXT")
                        .HasColumnName("emotional_state_observed");

                    b.Property<string>("FollowUpActions")
                        .HasColumnType("TEXT")
                        .HasColumnName("follow_up_actions");

                    b.Property<string>("InterventionsApplied")
                        .HasColumnType("TEXT")
                        .HasColumnName("interventions_applied");

                    b.Property<string>("NotesRestricted")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes_restricted");

                    b.Property<string>("ProgressNoted")
                        .HasColumnType("TEXT")
                        .HasColumnName("progress_noted");

                    b.Property<string>("ReferralMade")
                        .HasColumnType("TEXT")
                        .HasColumnName("referral_made");

                    b.Property<string>("ResidentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("resident_id");

                    b.Property<DateOnly?>("SessionDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_date");

                    b.Property<string>("SessionDurationMinutes")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_duration_minutes");

                    b.Property<string>("SessionNarrative")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_narrative");

                    b.Property<string>("SessionType")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_type");

                    b.Property<string>("SocialWorker")
                        .HasColumnType("TEXT")
                        .HasColumnName("social_worker");

                    b.HasKey("RecordingId");

                    b.ToTable("process_recordings", (string)null);
                });

            modelBuilder.Entity("Intex2026API.Models.PublicImpactSnapshot", b =>
                {
                    b.Property<string>("SnapshotId")
                        .HasColumnType("TEXT")
                        .HasColumnName("snapshot_id");

                    b.Property<string>("Headline")
                        .HasColumnType("TEXT")
                        .HasColumnName("headline");

                    b.Property<string>("IsPublished")
                        .HasColumnType("TEXT")
                        .HasColumnName("is_published");

                    b.Property<string>("MetricPayloadJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("metric_payload_json");

                    b.Property<DateOnly?>("PublishedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("published_at");

                    b.Property<DateOnly?>("SnapshotDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("snapshot_date");

                    b.Property<string>("SummaryText")
                        .HasColumnType("TEXT")
                        .HasColumnName("summary_text");

                    b.HasKey("SnapshotId");

                    b.ToTable("public_impact_snapshots", (string)null);
                });

            modelBuilder.Entity("Intex2026API.Models.Resident", b =>
                {
                    b.Property<string>("ResidentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("resident_id");

                    b.Property<string>("AgeUponAdmission")
                        .HasColumnType("TEXT")
                        .HasColumnName("age_upon_admission");

                    b.Property<string>("AssignedSocialWorker")
                        .HasColumnType("TEXT")
                        .HasColumnName("assigned_social_worker");

                    b.Property<string>("BirthStatus")
                        .HasColumnType("TEXT")
                        .HasColumnName("birth_status");

                    b.Property<string>("CaseCategory")
                        .HasColumnType("TEXT")
                        .HasColumnName("case_category");

                    b.Property<string>("CaseControlNo")
                        .HasColumnType("TEXT")
                        .HasColumnName("case_control_no");

                    b.Property<string>("CaseStatus")
                        .HasColumnType("TEXT")
                        .HasColumnName("case_status");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentRiskLevel")
                        .HasColumnType("TEXT")
                        .HasColumnName("current_risk_level");

                    b.Property<DateOnly?>("DateCaseStudyPrepared")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_case_study_prepared");

                    b.Property<DateOnly?>("DateClosed")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_closed");

                    b.Property<DateOnly?>("DateColbObtained")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_colb_obtained");

                    b.Property<DateOnly?>("DateColbRegistered")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_colb_registered");

                    b.Property<DateOnly?>("DateEnrolled")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_enrolled");

                    b.Property<DateOnly?>("DateOfAdmission")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_of_admission");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("FamilyIndigenous")
                        .HasColumnType("TEXT")
                        .HasColumnName("family_indigenous");

                    b.Property<string>("FamilyInformalSettler")
                        .HasColumnType("TEXT")
                        .HasColumnName("family_informal_settler");

                    b.Property<string>("FamilyIs4ps")
                        .HasColumnType("TEXT")
                        .HasColumnName("family_is_4ps");

                    b.Property<string>("FamilyParentPwd")
                        .HasColumnType("TEXT")
                        .HasColumnName("family_parent_pwd");

                    b.Property<string>("FamilySoloParent")
                        .HasColumnType("TEXT")
                        .HasColumnName("family_solo_parent");

                    b.Property<string>("HasSpecialNeeds")
                        .HasColumnType("TEXT")
                        .HasColumnName("has_special_needs");

                    b.Property<string>("InitialCaseAssessment")
                        .HasColumnType("TEXT")
                        .HasColumnName("initial_case_assessment");

                    b.Property<string>("InitialRiskLevel")
                        .HasColumnType("TEXT")
                        .HasColumnName("initial_risk_level");

                    b.Property<string>("InternalCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("internal_code");

                    b.Property<string>("IsPwd")
                        .HasColumnType("TEXT")
                        .HasColumnName("is_pwd");

                    b.Property<string>("LengthOfStay")
                        .HasColumnType("TEXT")
                        .HasColumnName("length_of_stay");

                    b.Property<string>("NotesRestricted")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes_restricted");

                    b.Property<string>("PlaceOfBirth")
                        .HasColumnType("TEXT")
                        .HasColumnName("place_of_birth");

                    b.Property<string>("PresentAge")
                        .HasColumnType("TEXT")
                        .HasColumnName("present_age");

                    b.Property<string>("PwdType")
                        .HasColumnType("TEXT")
                        .HasColumnName("pwd_type");

                    b.Property<string>("ReferralSource")
                        .HasColumnType("TEXT")
                        .HasColumnName("referral_source");

                    b.Property<string>("ReferringAgencyPerson")
                        .HasColumnType("TEXT")
                        .HasColumnName("referring_agency_person");

                    b.Property<string>("ReintegrationStatus")
                        .HasColumnType("TEXT")
                        .HasColumnName("reintegration_status");

                    b.Property<string>("ReintegrationType")
                        .HasColumnType("TEXT")
                        .HasColumnName("reintegration_type");

                    b.Property<string>("Religion")
                        .HasColumnType("TEXT")
                        .HasColumnName("religion");

                    b.Property<string>("SafehouseId")
                        .HasColumnType("TEXT")
                        .HasColumnName("safehouse_id");

                    b.Property<string>("Sex")
                        .HasColumnType("TEXT")
                        .HasColumnName("sex");

                    b.Property<string>("SpecialNeedsDiagnosis")
                        .HasColumnType("TEXT")
                        .HasColumnName("special_needs_diagnosis");

                    b.Property<string>("SubCatAtRisk")
                        .HasColumnType("TEXT")
                        .HasColumnName("sub_cat_at_risk");

                    b.Property<string>("SubCatChildLabor")
                        .HasColumnType("TEXT")
                        .HasColumnName("sub_cat_child_labor");

                    b.Property<string>("SubCatChildWithHiv")
                        .HasColumnType("TEXT")
                        .HasColumnName("sub_cat_child_with_hiv");

                    b.Property<string>("SubCatCicl")
                        .HasColumnType("TEXT")
                        .HasColumnName("sub_cat_cicl");

                    b.Property<string>("SubCatOrphaned")
                        .HasColumnType("TEXT")
                        .HasColumnName("sub_cat_orphaned");

                    b.Property<string>("SubCatOsaec")
                        .HasColumnType("TEXT")
                        .HasColumnName("sub_cat_osaec");

                    b.Property<string>("SubCatPhysicalAbuse")
                        .HasColumnType("TEXT")
                        .HasColumnName("sub_cat_physical_abuse");

                    b.Property<string>("SubCatSexualAbuse")
                        .HasColumnType("TEXT")
                        .HasColumnName("sub_cat_sexual_abuse");

                    b.Property<string>("SubCatStreetChild")
                        .HasColumnType("TEXT")
                        .HasColumnName("sub_cat_street_child");

                    b.Property<string>("SubCatTrafficked")
                        .HasColumnType("TEXT")
                        .HasColumnName("sub_cat_trafficked");

                    b.HasKey("ResidentId");

                    b.ToTable("residents", (string)null);
                });

            modelBuilder.Entity("Intex2026API.Models.Safehouse", b =>
                {
                    b.Property<string>("SafehouseId")
                        .HasColumnType("TEXT")
                        .HasColumnName("safehouse_id");

                    b.Property<string>("CapacityGirls")
                        .HasColumnType("TEXT")
                        .HasColumnName("capacity_girls");

                    b.Property<string>("CapacityStaff")
                        .HasColumnType("TEXT")
                        .HasColumnName("capacity_staff");

                    b.Property<string>("City")
                        .HasColumnType("TEXT")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT")
                        .HasColumnName("country");

                    b.Property<string>("CurrentOccupancy")
                        .HasColumnType("TEXT")
                        .HasColumnName("current_occupancy");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<DateOnly?>("OpenDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("open_date");

                    b.Property<string>("Province")
                        .HasColumnType("TEXT")
                        .HasColumnName("province");

                    b.Property<string>("Region")
                        .HasColumnType("TEXT")
                        .HasColumnName("region");

                    b.Property<string>("SafehouseCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("safehouse_code");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("SafehouseId");

                    b.ToTable("safehouses", (string)null);
                });

            modelBuilder.Entity("Intex2026API.Models.SafehouseMonthlyMetric", b =>
                {
                    b.Property<string>("MetricId")
                        .HasColumnType("TEXT")
                        .HasColumnName("metric_id");

                    b.Property<string>("ActiveResidents")
                        .HasColumnType("TEXT")
                        .HasColumnName("active_residents");

                    b.Property<decimal?>("AvgEducationProgress")
                        .HasColumnType("TEXT")
                        .HasColumnName("avg_education_progress");

                    b.Property<decimal?>("AvgHealthScore")
                        .HasColumnType("TEXT")
                        .HasColumnName("avg_health_score");

                    b.Property<string>("HomeVisitationCount")
                        .HasColumnType("TEXT")
                        .HasColumnName("home_visitation_count");

                    b.Property<string>("IncidentCount")
                        .HasColumnType("TEXT")
                        .HasColumnName("incident_count");

                    b.Property<DateOnly?>("MonthEnd")
                        .HasColumnType("TEXT")
                        .HasColumnName("month_end");

                    b.Property<DateOnly?>("MonthStart")
                        .HasColumnType("TEXT")
                        .HasColumnName("month_start");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("ProcessRecordingCount")
                        .HasColumnType("TEXT")
                        .HasColumnName("process_recording_count");

                    b.Property<string>("SafehouseId")
                        .HasColumnType("TEXT")
                        .HasColumnName("safehouse_id");

                    b.HasKey("MetricId");

                    b.ToTable("safehouse_monthly_metrics", (string)null);
                });

            modelBuilder.Entity("Intex2026API.Models.SocialMediaPost", b =>
                {
                    b.Property<string>("PostId")
                        .HasColumnType("TEXT")
                        .HasColumnName("post_id");

                    b.Property<decimal?>("AvgViewDurationSeconds")
                        .HasColumnType("TEXT")
                        .HasColumnName("avg_view_duration_seconds");

                    b.Property<decimal?>("BoostBudgetPhp")
                        .HasColumnType("TEXT")
                        .HasColumnName("boost_budget_php");

                    b.Property<string>("CallToActionType")
                        .HasColumnType("TEXT")
                        .HasColumnName("call_to_action_type");

                    b.Property<string>("CampaignName")
                        .HasColumnType("TEXT")
                        .HasColumnName("campaign_name");

                    b.Property<string>("Caption")
                        .HasColumnType("TEXT")
                        .HasColumnName("caption");

                    b.Property<string>("CaptionLength")
                        .HasColumnType("TEXT")
                        .HasColumnName("caption_length");

                    b.Property<string>("ClickThroughs")
                        .HasColumnType("TEXT")
                        .HasColumnName("click_throughs");

                    b.Property<string>("Comments")
                        .HasColumnType("TEXT")
                        .HasColumnName("comments");

                    b.Property<string>("ContentTopic")
                        .HasColumnType("TEXT")
                        .HasColumnName("content_topic");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DayOfWeek")
                        .HasColumnType("TEXT")
                        .HasColumnName("day_of_week");

                    b.Property<string>("DonationReferrals")
                        .HasColumnType("TEXT")
                        .HasColumnName("donation_referrals");

                    b.Property<decimal?>("EngagementRate")
                        .HasColumnType("TEXT")
                        .HasColumnName("engagement_rate");

                    b.Property<decimal?>("EstimatedDonationValuePhp")
                        .HasColumnType("TEXT")
                        .HasColumnName("estimated_donation_value_php");

                    b.Property<string>("FeaturesResidentStory")
                        .HasColumnType("TEXT")
                        .HasColumnName("features_resident_story");

                    b.Property<string>("FollowerCountAtPost")
                        .HasColumnType("TEXT")
                        .HasColumnName("follower_count_at_post");

                    b.Property<decimal?>("Forwards")
                        .HasColumnType("TEXT")
                        .HasColumnName("forwards");

                    b.Property<string>("HasCallToAction")
                        .HasColumnType("TEXT")
                        .HasColumnName("has_call_to_action");

                    b.Property<string>("Hashtags")
                        .HasColumnType("TEXT")
                        .HasColumnName("hashtags");

                    b.Property<string>("Impressions")
                        .HasColumnType("TEXT")
                        .HasColumnName("impressions");

                    b.Property<string>("IsBoosted")
                        .HasColumnType("TEXT")
                        .HasColumnName("is_boosted");

                    b.Property<string>("Likes")
                        .HasColumnType("TEXT")
                        .HasColumnName("likes");

                    b.Property<string>("MediaType")
                        .HasColumnType("TEXT")
                        .HasColumnName("media_type");

                    b.Property<string>("MentionsCount")
                        .HasColumnType("TEXT")
                        .HasColumnName("mentions_count");

                    b.Property<string>("NumHashtags")
                        .HasColumnType("TEXT")
                        .HasColumnName("num_hashtags");

                    b.Property<string>("Platform")
                        .HasColumnType("TEXT")
                        .HasColumnName("platform");

                    b.Property<string>("PlatformPostId")
                        .HasColumnType("TEXT")
                        .HasColumnName("platform_post_id");

                    b.Property<string>("PostHour")
                        .HasColumnType("TEXT")
                        .HasColumnName("post_hour");

                    b.Property<string>("PostType")
                        .HasColumnType("TEXT")
                        .HasColumnName("post_type");

                    b.Property<string>("PostUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("post_url");

                    b.Property<string>("ProfileVisits")
                        .HasColumnType("TEXT")
                        .HasColumnName("profile_visits");

                    b.Property<string>("Reach")
                        .HasColumnType("TEXT")
                        .HasColumnName("reach");

                    b.Property<string>("Saves")
                        .HasColumnType("TEXT")
                        .HasColumnName("saves");

                    b.Property<string>("SentimentTone")
                        .HasColumnType("TEXT")
                        .HasColumnName("sentiment_tone");

                    b.Property<string>("Shares")
                        .HasColumnType("TEXT")
                        .HasColumnName("shares");

                    b.Property<decimal?>("SubscriberCountAtPost")
                        .HasColumnType("TEXT")
                        .HasColumnName("subscriber_count_at_post");

                    b.Property<decimal?>("VideoViews")
                        .HasColumnType("TEXT")
                        .HasColumnName("video_views");

                    b.Property<decimal?>("WatchTimeSeconds")
                        .HasColumnType("TEXT")
                        .HasColumnName("watch_time_seconds");

                    b.HasKey("PostId");

                    b.ToTable("social_media_posts", (string)null);
                });

            modelBuilder.Entity("Intex2026API.Models.Supporter", b =>
                {
                    b.Property<string>("SupporterId")
                        .HasColumnType("TEXT")
                        .HasColumnName("supporter_id");

                    b.Property<string>("AcquisitionChannel")
                        .HasColumnType("TEXT")
                        .HasColumnName("acquisition_channel");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT")
                        .HasColumnName("country");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<DateOnly?>("FirstDonationDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("first_donation_date");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_name");

                    b.Property<string>("OrganizationName")
                        .HasColumnType("TEXT")
                        .HasColumnName("organization_name");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT")
                        .HasColumnName("phone");

                    b.Property<string>("Region")
                        .HasColumnType("TEXT")
                        .HasColumnName("region");

                    b.Property<string>("RelationshipType")
                        .HasColumnType("TEXT")
                        .HasColumnName("relationship_type");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("SupporterType")
                        .HasColumnType("TEXT")
                        .HasColumnName("supporter_type");

                    b.HasKey("SupporterId");

                    b.ToTable("supporters", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
